const caseStudies = [
  {id:'guardrail',number:'01',title:'Chatbot LLM dengan Guardrail',level:'Menengah–Lanjut',path:'notebooks/studi-kasus-guardrail-xnli-llm.ipynb',summary:'Membangun lapisan pengaman sebelum dan sesudah generasi menggunakan zero-shot XNLI serta LLM Qwen; Llama menjadi alternatif generator.',theory:['Natural Language Inference untuk klasifikasi batas domain','Input guard, output guard, refusal, dan audit log','Threshold, false refusal, unsafe compliance, serta evaluasi per kategori'],experiment:'Bandingkan classifier-only guardrail, prompt-only guardrail, dan gabungan keduanya pada input aman, out-of-domain, prompt injection, serta harmful request.',metrics:'Safe response rate, unsafe compliance, false refusal, macro-F1 guard classifier, dan latency.'},
  {id:'lora',number:'02',title:'Fine-Tuning LLM dengan LoRA dan QLoRA',level:'Lanjut',path:'notebooks/studi-kasus-lora-qlora.ipynb',summary:'Melakukan adaptation sederhana pada Qwen kecil menggunakan low-rank adapter dan membandingkan LoRA dengan base model 4-bit pada QLoRA.',theory:['Low-rank update ΔW=BA dan trainable parameter','Quantization 4-bit, NF4, double quantization, compute dtype','Dataset instruction, masking label, checkpoint adapter, dan overfitting'],experiment:'Gunakan dataset instruction kecil, ukur trainable parameters, memory, loss, waktu, dan kualitas keluaran sebelum–sesudah adaptation.',metrics:'Validation loss, task accuracy/ROUGE, trainable parameter ratio, peak GPU memory, dan waktu training.'},
  {id:'chunking',number:'03',title:'RAG dengan Ragam Strategi Chunking',level:'Menengah',path:'notebooks/studi-kasus-rag-ragam-chunking.ipynb',summary:'Membandingkan fixed-size, sentence, recursive, structure-aware, dan semantic chunking pada corpus dan query yang sama.',theory:['Boundary, overlap, context completeness, dan redundancy','Hubungan chunking dengan embedding serta top-k retrieval','Ground-truth relevant passage dan evaluasi retrieval sebelum generation'],experiment:'Jalankan kelima strategi, bentuk index masing-masing, lalu bandingkan relevant-context retrieval serta contoh kegagalannya.',metrics:'Recall@k, MRR, context precision, rata-rata panjang chunk, redundancy, dan latency.'},
  {id:'hybrid',number:'04',title:'Hybrid RAG: Sparse + Dense + Reranker',level:'Lanjut',path:'notebooks/studi-kasus-hybrid-rag.ipynb',summary:'Menggabungkan BM25 yang kuat pada exact term dengan dense retrieval yang kuat pada parafrasa, kemudian melakukan rank fusion dan reranking.',theory:['BM25, dense cosine similarity, score normalization','Reciprocal Rank Fusion dan weighted fusion','Cross-encoder reranker serta cost–quality trade-off'],experiment:'Bandingkan BM25-only, dense-only, hybrid fusion, dan hybrid + reranker pada query istilah khusus serta query parafrasa.',metrics:'Recall@k, MRR, nDCG@k, reranking gain, latency, dan jumlah relevant document.'},
  {id:'sentiment',number:'05',title:'Analisis Sentimen Bahasa Indonesia',level:'Dasar–Menengah',path:'notebooks/studi-kasus-nlp-sentiment.ipynb',summary:'Membangun baseline TF–IDF + logistic regression dan membandingkannya dengan pretrained Transformer.',theory:['Preprocessing, class imbalance, dan baseline','Macro vs micro F1 serta confusion matrix','Negasi, ironi, domain shift, dan error taxonomy'],experiment:'Bandingkan word n-gram, character n-gram, dan Transformer pada split identik.',metrics:'Accuracy, macro-F1, precision/recall per kelas, dan inference time.'},
  {id:'ner',number:'06',title:'Named-Entity Recognition',level:'Menengah',path:'notebooks/studi-kasus-nlp-ner.ipynb',summary:'Mengenali person, organization, location, dan entitas domain dengan skema BIO serta token classification.',theory:['BIO tagging dan alignment kata–subword','Token classification dan ignored label -100','Entity-level precision, recall, F1, dan boundary error'],experiment:'Periksa pengaruh subword alignment serta domain entity yang tidak muncul pada pretraining.',metrics:'Entity-level F1, exact boundary accuracy, dan error per entity type.'},
  {id:'summarization',number:'07',title:'Text Summarization dan Evaluasi',level:'Menengah',path:'notebooks/studi-kasus-nlp-summarization.ipynb',summary:'Membandingkan extractive baseline dengan abstractive summarization serta memeriksa factual consistency.',theory:['Extractive vs abstractive summary','Length control, decoding, dan hallucination','ROUGE, semantic similarity, coverage, dan human rubric'],experiment:'Bandingkan baseline pemilihan kalimat dengan pretrained seq2seq pada dokumen pendek.',metrics:'ROUGE-1/L, compression ratio, factual error count, relevance, dan fluency.'},
  {id:'similarity',number:'08',title:'Semantic Search dan Similarity',level:'Dasar–Menengah',path:'notebooks/studi-kasus-nlp-semantic-search.ipynb',summary:'Membentuk mesin pencari semantik multilingual dan membandingkannya dengan lexical matching.',theory:['Bi-encoder embedding dan cosine similarity','Query/document representation serta top-k','Hard negative, threshold, dan out-of-domain query'],experiment:'Uji query exact keyword, parafrasa, singkatan, dan campur kode pada sparse serta dense search.',metrics:'Recall@k, MRR, hit rate, threshold rejection, dan latency.'}
];

function renderCaseStudies(){
  const root=document.getElementById('case-study-grid');
  if(!root)return;
  root.innerHTML=caseStudies.map(c=>`<article class="study-card"><div class="study-top"><span class="study-num">${c.number}</span><span class="study-level">${c.level}</span></div><h3>${c.title}</h3><p>${c.summary}</p><details><summary>Teori dan rancangan eksperimen</summary><div class="study-detail"><h4>Konsep yang dipelajari</h4><ul>${c.theory.map(x=>`<li>${x}</li>`).join('')}</ul><h4>Eksperimen</h4><p>${c.experiment}</p><h4>Evaluasi</h4><p>${c.metrics}</p></div></details><div class="run-actions"><button class="run-btn colab" onclick="openNotebook('colab','${c.path}')">Jalankan di Google Colab</button></div><p><small>Simpan perubahan melalui <b>File → Save a copy in Drive</b>.</small></p></article>`).join('');
}
